services:
  postgres:
    image: postgres
    container_name: "postgres_festival"
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: festival
